export const REPEAT_MENTIONED_WORDS_POSSIBILITY = 0.1;
export const IS_TRANSLATED_WORD_IN_QUESTION_POSSIBILITY = 0.2;
export const IS_MANUAL_TRANSLATION_POSSIBILITY = 0.5;
export const LOCAL_STORAGE_MENTIONED_WORDS_KEY = "mentionedWords";